### ISSUE TITLE
Total Aportado en la sección evolución es menor del real

### ISSUE THREAD

**Issue by ferrercanedo** [victor-marino/xinsight#71]
En la grafica de evolución el valor mostrado de "total aportado" es inferior al real (y al que se muestra en la pestaña resumen

En mi caso hay un 10% de diferencia, no es exacto pero es curioso que los decimales coinciden. La grafica en la app de indexa es correcto (no se si es error del api de indexa)

Si puedo aportar más información por privado sin problema

**Comment by victor-marino** [comment]
Hola!

Muchas gracias por reportar esto.

No he visto este fallo antes, pero estaba revisando el código y creo que seguramente sea la propia API de Indexa la que está devolviendo valores distintos.

Si te manejas con el tema de enviar API requests, puedes probar lo siguiente para tratar de confirmarlo:
1. Envía una request al endpoint `/accounts/{{account_number}}/performance`, reemplazando el token y tu número de cuenta:
```http
GET https://api.indexacapital.com/accounts/{{account_number}}/performance
X-AUTH-TOKEN: {{token}}
Accept: */*
```
2. En la respuesta, comprueba los siguientes datos:
`return.investment` -> El total aportado que se muestra en la pantalla de resumen.
`return.net_amounts` -> Serie acumulativa con el histórico de tus cantidades aportada a lo largo del tiempo, que se muestra en la gráfica de evolución.

Si todo está bien, el último valor de la serie `return.net_amounts` debería coincidir con el valor actual de `return.investment`. Por ejemplo para hoy, el último valor sería el que tiene fecha de ayer (`20240821`).

Si esos valores no te coinciden, significa que la API de Indexa está devolviendo dos valores diferentes. En ese caso les puedo preguntar si es normal que esto ocurra.

Si por contra los valore sí te coinciden pero mi app te muestra números distintos, dímelo y reviso bien el código a ver dónde podría estar el problema.

Saludos!

**Comment by ferrercanedo** [comment]
Gracias!

Es lo que dices, ya viene el valor incorrecto en el api. El valor "malo"
que tengo en net_amounts veo que es el mismo que viene en return.inflows

Un saludo,
Marcos

**Comment by victor-marino** [comment]
Gracias! Les preguntaré a ver por qué puede ser.

`return.inflows` sólo muestra las cantidades aportadas, sin tener en cuenta las retiradas (`return.outflows`). Mientras que `return.net_amounts` y `return.investment` deberían ser los inflows menos los outflows. No sé si has hecho retiradas, pero en cualquier caso yo sí que las he hecho y me coinciden bien los datos.

Se lo comento a los de Indexa a ver qué me dicen.

Gracias de nuevo!
Víctor.

**Comment by victor-marino** [comment]
Otra cosa que se me acaba de ocurrir:

Has hecho alguna aportación recientemente? De ser así, has comprobado si la última fecha de la gráfica de evolución es posterior a la fecha en que se invirtió tu última aportación?

Estaba pensando que quizá los valores liquidativos de los fondos aún no se hubiesen actualizado con los últimos datos, y al no tener datos más recientes la gráfica sólo llegue hasta una fecha anterior a tu aportación.

Ya me dices.

**Comment by ferrercanedo** [comment]
Hola! En mi caso no he hecho retiradas pero si aportaciones sucesivas

Y si que he dejado unos dias desde la última aportación para ver si
actualizaba pero no es el caso, se mantiene con esa diferencia

Un saludo,
Marcos

**Comment by victor-marino** [comment]
Vale, entonces descartamos eso. Ya les he preguntado a los de Indexa, a ver qué me dicen.

**Comment by victor-marino** [comment]
Hola de nuevo @ferrercanedo.

Me comentan que no es normal esto que te ocurre, los valores deberían coincidir, y me preguntan si podrías contactar con ellos para que echen un ojo.

La persona de IT que lo lleva está disponible en Telegram (no sé si lo usas). Su contacto es @jaguadop.

Si no, me han dicho que les puedes escribir a info@indexacapital.com preguntando por Juan Aguado.

Saludos!
